apiVersion: v1
kind: Service
metadata:
    name: "intellipixaks-4a67"
    labels:
        app: "intellipixaks-4a67"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "intellipixaks-4a67"